import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Mail, Eye } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PageHeader } from "@/components/admin/PageHeader";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/admin/email-logs")({
  component: EmailLogsPage,
});

type EmailLog = {
  id: string;
  recipient_email: string;
  subject: string;
  body: string;
  template: string | null;
  status: string;
  provider_response: unknown;
  created_at: string;
};

function statusVariant(s: string): "default" | "secondary" | "destructive" | "outline" {
  if (s === "sent") return "default";
  if (s === "failed") return "destructive";
  if (s === "stubbed") return "secondary";
  return "outline";
}

function EmailLogsPage() {
  const [q, setQ] = useState("");
  const [viewing, setViewing] = useState<EmailLog | null>(null);

  const { data = [], isLoading, error } = useQuery({
    queryKey: ["admin-email-logs"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("email_logs")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(500);
      if (error) throw error;
      return (data as EmailLog[]) ?? [];
    },
  });

  const filtered = data.filter((r) => {
    if (!q.trim()) return true;
    const n = q.toLowerCase();
    return (
      r.recipient_email.toLowerCase().includes(n) ||
      r.subject.toLowerCase().includes(n) ||
      r.template?.toLowerCase().includes(n) ||
      r.status.toLowerCase().includes(n)
    );
  });

  return (
    <div>
      <PageHeader
        title="Email Logs"
        description="Credential and notification emails generated by the system. In stub mode, emails are recorded here but not actually delivered."
      />
      <div className="mb-4 max-w-md">
        <Input placeholder="Search by recipient, subject, status…" value={q} onChange={(e) => setQ(e.target.value)} />
      </div>
      <div className="rounded-lg border bg-card overflow-x-auto shadow-[var(--shadow-card)]">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Sent</TableHead>
              <TableHead>Recipient</TableHead>
              <TableHead>Subject</TableHead>
              <TableHead>Template</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              <TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">Loading…</TableCell></TableRow>
            ) : error ? (
              <TableRow><TableCell colSpan={6} className="py-10 text-center text-destructive">{(error as Error).message}</TableCell></TableRow>
            ) : filtered.length === 0 ? (
              <TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">
                <Mail className="mx-auto mb-2 h-8 w-8 opacity-40" />
                No email logs yet.
              </TableCell></TableRow>
            ) : filtered.map((r) => (
              <TableRow key={r.id}>
                <TableCell className="text-xs text-muted-foreground whitespace-nowrap">{new Date(r.created_at).toLocaleString()}</TableCell>
                <TableCell>{r.recipient_email}</TableCell>
                <TableCell className="max-w-[260px] truncate">{r.subject}</TableCell>
                <TableCell><Badge variant="outline" className="capitalize">{r.template ?? "—"}</Badge></TableCell>
                <TableCell><Badge variant={statusVariant(r.status)} className="capitalize">{r.status}</Badge></TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="icon" onClick={() => setViewing(r)} title="View">
                    <Eye className="h-4 w-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <Dialog open={!!viewing} onOpenChange={(o) => !o && setViewing(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="truncate">{viewing?.subject}</DialogTitle>
          </DialogHeader>
          <div className="space-y-2 text-sm">
            <div><span className="text-muted-foreground">To:</span> {viewing?.recipient_email}</div>
            <div><span className="text-muted-foreground">Status:</span> <Badge variant={statusVariant(viewing?.status ?? "")} className="capitalize">{viewing?.status}</Badge></div>
            <div><span className="text-muted-foreground">Sent:</span> {viewing && new Date(viewing.created_at).toLocaleString()}</div>
            <pre className="max-h-80 overflow-y-auto whitespace-pre-wrap rounded-md border bg-muted/30 p-3 text-xs">{viewing?.body}</pre>
            {viewing?.provider_response ? (
              <details className="text-xs">
                <summary className="cursor-pointer text-muted-foreground">Provider response</summary>
                <pre className="mt-1 overflow-x-auto rounded-md border bg-muted/30 p-2">{JSON.stringify(viewing.provider_response, null, 2)}</pre>
              </details>
            ) : null}
          </div>
          <DialogFooter><Button variant="outline" onClick={() => setViewing(null)}>Close</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
