/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherSchedulesRouteImport } from './routes/teacher.schedules'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherCheckInRecordsRouteImport } from './routes/teacher.check-in-records'
import { Route as TeacherCalendarRouteImport } from './routes/teacher.calendar'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLocationRouteImport } from './routes/admin.location'
import { Route as AdminGeofencingRouteImport } from './routes/admin.geofencing'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminEmailLogsRouteImport } from './routes/admin.email-logs'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAcademicRouteImport } from './routes/admin.academic'
import { Route as TeacherAttendanceSessionScheduleIdRouteImport } from './routes/teacher.attendance-session.$scheduleId'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students_.$id'
import { Route as ApiPublicHooksDispatchSmsRouteImport } from './routes/api/public/hooks/dispatch-sms'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherSchedulesRoute = TeacherSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCheckInRecordsRoute = TeacherCheckInRecordsRouteImport.update({
  id: '/check-in-records',
  path: '/check-in-records',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationRoute = AdminLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeofencingRoute = AdminGeofencingRouteImport.update({
  id: '/geofencing',
  path: '/geofencing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailLogsRoute = AdminEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicRoute = AdminAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherAttendanceSessionScheduleIdRoute =
  TeacherAttendanceSessionScheduleIdRouteImport.update({
    id: '/attendance-session/$scheduleId',
    path: '/attendance-session/$scheduleId',
    getParentRoute: () => TeacherRoute,
  } as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students_/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksDispatchSmsRoute =
  ApiPublicHooksDispatchSmsRouteImport.update({
    id: '/api/public/hooks/dispatch-sms',
    path: '/api/public/hooks/dispatch-sms',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/geofencing': typeof AdminGeofencingRoute
  '/admin/location': typeof AdminLocationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/check-in-records': typeof TeacherCheckInRecordsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/schedules': typeof TeacherSchedulesRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/teacher/attendance-session/$scheduleId': typeof TeacherAttendanceSessionScheduleIdRoute
  '/api/public/hooks/dispatch-sms': typeof ApiPublicHooksDispatchSmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/geofencing': typeof AdminGeofencingRoute
  '/admin/location': typeof AdminLocationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/check-in-records': typeof TeacherCheckInRecordsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/schedules': typeof TeacherSchedulesRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/teacher/attendance-session/$scheduleId': typeof TeacherAttendanceSessionScheduleIdRoute
  '/api/public/hooks/dispatch-sms': typeof ApiPublicHooksDispatchSmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/email-logs': typeof AdminEmailLogsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/geofencing': typeof AdminGeofencingRoute
  '/admin/location': typeof AdminLocationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/check-in-records': typeof TeacherCheckInRecordsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/schedules': typeof TeacherSchedulesRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/students_/$id': typeof AdminStudentsIdRoute
  '/teacher/attendance-session/$scheduleId': typeof TeacherAttendanceSessionScheduleIdRoute
  '/api/public/hooks/dispatch-sms': typeof ApiPublicHooksDispatchSmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/admin/academic'
    | '/admin/audit-logs'
    | '/admin/broadcast'
    | '/admin/calendar'
    | '/admin/departments'
    | '/admin/devices'
    | '/admin/email-logs'
    | '/admin/exports'
    | '/admin/geofencing'
    | '/admin/location'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/check-in-records'
    | '/teacher/notifications'
    | '/teacher/reports'
    | '/teacher/schedules'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/students/$id'
    | '/teacher/attendance-session/$scheduleId'
    | '/api/public/hooks/dispatch-sms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/academic'
    | '/admin/audit-logs'
    | '/admin/broadcast'
    | '/admin/calendar'
    | '/admin/departments'
    | '/admin/devices'
    | '/admin/email-logs'
    | '/admin/exports'
    | '/admin/geofencing'
    | '/admin/location'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/check-in-records'
    | '/teacher/notifications'
    | '/teacher/reports'
    | '/teacher/schedules'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/students/$id'
    | '/teacher/attendance-session/$scheduleId'
    | '/api/public/hooks/dispatch-sms'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/admin/academic'
    | '/admin/audit-logs'
    | '/admin/broadcast'
    | '/admin/calendar'
    | '/admin/departments'
    | '/admin/devices'
    | '/admin/email-logs'
    | '/admin/exports'
    | '/admin/geofencing'
    | '/admin/location'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/schedules'
    | '/admin/sections'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/attendance'
    | '/student/calendar'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/teacher/attendance'
    | '/teacher/calendar'
    | '/teacher/check-in-records'
    | '/teacher/notifications'
    | '/teacher/reports'
    | '/teacher/schedules'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/students_/$id'
    | '/teacher/attendance-session/$scheduleId'
    | '/api/public/hooks/dispatch-sms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  ApiPublicHooksDispatchSmsRoute: typeof ApiPublicHooksDispatchSmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/schedules': {
      id: '/teacher/schedules'
      path: '/schedules'
      fullPath: '/teacher/schedules'
      preLoaderRoute: typeof TeacherSchedulesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/check-in-records': {
      id: '/teacher/check-in-records'
      path: '/check-in-records'
      fullPath: '/teacher/check-in-records'
      preLoaderRoute: typeof TeacherCheckInRecordsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/location': {
      id: '/admin/location'
      path: '/location'
      fullPath: '/admin/location'
      preLoaderRoute: typeof AdminLocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geofencing': {
      id: '/admin/geofencing'
      path: '/geofencing'
      fullPath: '/admin/geofencing'
      preLoaderRoute: typeof AdminGeofencingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-logs': {
      id: '/admin/email-logs'
      path: '/email-logs'
      fullPath: '/admin/email-logs'
      preLoaderRoute: typeof AdminEmailLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic': {
      id: '/admin/academic'
      path: '/academic'
      fullPath: '/admin/academic'
      preLoaderRoute: typeof AdminAcademicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/attendance-session/$scheduleId': {
      id: '/teacher/attendance-session/$scheduleId'
      path: '/attendance-session/$scheduleId'
      fullPath: '/teacher/attendance-session/$scheduleId'
      preLoaderRoute: typeof TeacherAttendanceSessionScheduleIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/students_/$id': {
      id: '/admin/students_/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/dispatch-sms': {
      id: '/api/public/hooks/dispatch-sms'
      path: '/api/public/hooks/dispatch-sms'
      fullPath: '/api/public/hooks/dispatch-sms'
      preLoaderRoute: typeof ApiPublicHooksDispatchSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicRoute: typeof AdminAcademicRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminEmailLogsRoute: typeof AdminEmailLogsRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminGeofencingRoute: typeof AdminGeofencingRoute
  AdminLocationRoute: typeof AdminLocationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicRoute: AdminAcademicRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminEmailLogsRoute: AdminEmailLogsRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminGeofencingRoute: AdminGeofencingRoute,
  AdminLocationRoute: AdminLocationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherCheckInRecordsRoute: typeof TeacherCheckInRecordsRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSchedulesRoute: typeof TeacherSchedulesRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherAttendanceSessionScheduleIdRoute: typeof TeacherAttendanceSessionScheduleIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherCheckInRecordsRoute: TeacherCheckInRecordsRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSchedulesRoute: TeacherSchedulesRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherAttendanceSessionScheduleIdRoute:
    TeacherAttendanceSessionScheduleIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  ApiPublicHooksDispatchSmsRoute: ApiPublicHooksDispatchSmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
